### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by NouraAlgohary** [7oSkaaa/LeetCode_DailyChallenge_2023#1151]
I had a problem with the repository on my local PC. I tried to clone it but the file is empty. I’m not sure what’s causing this issue. Can someone help me troubleshoot this problem?

**Comment by 7oSkaaa** [comment]
Try to write this command inside the repo folder:

`git restore --source=HEAD :/`

**Comment by NouraAlgohary** [comment]
```
error: invalid path '05- May/19- Is Graph Bipartite?/.gitkeep'
error: invalid path '05- May/19- Is Graph Bipartite?/19- Is Graph Bipartite? (Ahmed Hossam).cpp
```

**Comment by NouraAlgohary** [comment]
Resolved, thanks!
